# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'CustomAuth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomAuth

  pod 'AWSMobileClient', '~> 2.12.0'
  pod 'PhoneNumberKit', '~> 3.1'
  pod 'Toast-Swift', '~> 5.0.0'

end
